poll/urls.py
from django.conf.urls import *
from . import views

urlpatterns = patterns('',
    url(r"^$", views.polls, name="polls"),
    url(r"^(\d+)/submissions.csv$", views.responses_as_csv),    
    url(r"^new/$", views.new_poll),
    url(r"^(\d+)/responses/$", views.view_responses, name="poll-responses"),
    url(r"^(?P<poll_id>\d+)/responses/module/$", views.view_responses,  {'as_module':True}, name="poll-responses-module"),    
    url(r"^responses/(\d+)/view/$", views.view_response),    
    url(r"^(\d+)/report/$", views.view_report, name="poll-report"),
    url(r"^(\d+)/report/(\d+)/$", views.view_report, name="poll-report"),
    url(r"^(?P<poll_id>\d+)/report/module/$", views.view_report, {'as_module':True}, name="poll-report-module"),
    url(r"^(\d+)/report/(\d+)/module/$", views.view_report, {'as_module':True}, name="poll-report-location-module"),

    url(r"^responses/(\d+)/edit/$", views.edit_response),
    url(r"^responses/(\d+)/apply/$", views.apply_response),
    url(r"^responses/(\d+)/apply_all/$", views.apply_all),
    url(r"^responses/(\d+)/delete/$", views.delete_response),
    url(r"^responses/(?P<poll_id>\d+)/stats/$", views.stats, name="poll-stats"),
    url(r"^responses/(?P<poll_id>\d+)/stats/(?P<location_id>\d+)/$", views.stats, name="poll-stats"),
    url(r"^responses/(?P<poll_id>\d+)/agestats/$", views.age_stats, name="poll-age-stats"),
    url(r"^responses/(?P<poll_id>\d+)/genderstats/$", views.gender_stats, name="poll-gender-stats"),
    url(r"^responses/(?P<poll_id>\d+)/numeric/$", views.number_details),
    url(r"^(\d+)/view/$", views.view_poll),
    url(r"^(\d+)/details/$", views.view_poll_details),
    url(r"^(\d+)/edit/$", views.edit_poll),
    url(r"^(\d+)/delete/$", views.delete_poll),
    url(r"^(\d+)/start/$", views.start_poll),
    url(r"^(\d+)/end/$", views.end_poll),
    url(r"^(\d+)/add_category/$", views.add_category),
    url(r"^(\d+)/edit_category/(\d+)/$", views.edit_category),
    url(r"^(\d+)/category/(\d+)/$", views.view_category),
    url(r"^(\d+)/delete_category/(\d+)/$", views.delete_category),
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/$", views.view_rule),    
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/edit/$", views.edit_rule),
    url(r"^(\d+)/category/(\d+)/rules/add/$", views.add_rule),    
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/delete/$", views.delete_rule),
    url(r"^(\d+)/category/(\d+)/rules/$", views.view_rules),
    url(r"^(\d+)/categories/add/$", views.add_category),
    url(r"^(\d+)/demo/", views.demo, name="demo"),
)

poll/models.py
import datetime
import difflib
from celery.task import task
import django
from django.db import models, transaction
from django.db.models import Sum, Avg, Count, Max, Min, StdDev
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import ugettext as _
from mptt.forms import TreeNodeChoiceField
from rapidsms.models import Contact, Connection

from eav import register
from eav.models import Value, Attribute

from generic.sorters import SimpleSorter

from rapidsms.contrib.locations.models import Location
from rapidsms.contrib.locations.nested import models as nested_models
from rapidsms_httprouter.models import Message, MessageBatch

from django.conf import settings
import re
from django.utils.translation import (ugettext, activate, deactivate)
from dateutil.relativedelta import relativedelta

import logging

log = logging.getLogger(__name__)

poll_started = django.dispatch.Signal(providing_args=[])

# The standard template allows for any amount of whitespace at the beginning,
# followed by the alias(es) for a particular category, followed by any non-
# alphabetical character, or the end of the message
STARTSWITH_PATTERN_TEMPLATE = '^\s*(%s)(\s|[^a-zA-Z]|$)'

CONTAINS_PATTERN_TEMPLATE = '^.*\s*(%s)(\s|[^a-zA-Z]|$)'

# This can be configurable from settings, but here's a default list of 
# accepted yes keywords
YES_WORDS = [_('yes'), _('yeah'), _('yep'), _('yay'), 'y']

# This can be configurable from settings, but here's a default list of
# accepted no keywords

NO_WORDS = [_('no'), _('nope'), _('nah'), _('nay'),  'n']


class ResponseForm(forms.Form):
    def __init__(self, data=None, **kwargs):
        response = kwargs.pop('response')
        if data:
            forms.Form.__init__(self, data, **kwargs)
        else:
            forms.Form.__init__(self, **kwargs)
        self.fields['categories'] = forms.ModelMultipleChoiceField(required=False,
                                                                   queryset=response.poll.categories.all(),
                                                                   initial=Category.objects.filter(
                                                                       pk__in=response.categories.values_list(
                                                                           'category', flat=True)))


class NumericResponseForm(ResponseForm):
    value = forms.FloatField()


class LocationResponseForm(ResponseForm):
    value = TreeNodeChoiceField(queryset=Location.objects.all(),
                                level_indicator=u'.', required=True)


class NameResponseForm(ResponseForm):
    value = forms.CharField()


class ResponseCategory(models.Model):
    category = models.ForeignKey('Category')
    response = models.ForeignKey('Response', related_name='categories')
    is_override = models.BooleanField(default=False)
    user = models.ForeignKey(User, null=True)


class Poll(models.Model):
    """
    Polls represent a simple-question, simple-response communication modality
    via SMS.  They can be thought of as a similar to a single datum in an XForm,
    although for now the only data types available are yes/no, free-form text, and
    numeric response.  Fairly simple idea, a poll is created, containing a question 
    (the outgoing messages), a list of contacts (those to poll) and an expected
    *type* of response.  The poll can be edited, contact lists modified, etc. via
    the web (the "user"), until it is eventually *started.*  When a poll is started,
    the outgoing question will be sent to all contacts, and any subsequent messages
    coming in from the contacts associated with this poll (until they are polled again)
    will be parsed (or attempted to be parsed) by this poll, and bucketed into a 
    particular category.
    
    FIXME: contact groups, if implemented in core or contrib, should be used here,
           instead of a many-to-many field
    """

    TYPE_TEXT = 't'
    TYPE_NUMERIC = 'n'
    TYPE_LOCATION = 'l'
    TYPE_REGISTRATION = 'r'

    RESPONSE_TYPE_ALL = 'a'# all all responses
    RESPONSE_TYPE_ONE = 'o' # allow only one

    RESPONSE_TYPE_CHOICES = (
        (RESPONSE_TYPE_ALL, _('Allow all')),
        (RESPONSE_TYPE_ONE, _('Allow one')),

    )

    TYPE_CHOICES = {
        TYPE_NUMERIC: dict(
            label=_('Numeric Response'),
            type=TYPE_NUMERIC,
            db_type=Attribute.TYPE_FLOAT,
            parser=None,
            view_template='polls/response_numeric_view.html',
            edit_template='polls/response_numeric_edit.html',
            report_columns=((('Text', 'text', True, 'message__text', SimpleSorter()),
                             ('Value', 'value', True, 'eav_values__value_float', SimpleSorter()),
                             ('Categories', 'categories', True, 'categories__category__name', SimpleSorter()))),
            edit_form=NumericResponseForm),
        TYPE_TEXT: dict(
            label=_('Free-form'),
            type=TYPE_TEXT,
            db_type=Attribute.TYPE_TEXT,
            parser=None,
            view_template='polls/response_text_view.html',
            edit_template='polls/response_text_edit.html',
            report_columns=(('Text', 'text', True, 'message__text', SimpleSorter()),
                            ('Categories', 'categories', True, 'categories__category__name', SimpleSorter())),
            edit_form=ResponseForm),
        TYPE_REGISTRATION: dict(
            label=_('Name/registration-based'),
            type=TYPE_REGISTRATION,
            db_type=Attribute.TYPE_TEXT,
            parser=None,
            view_template='polls/response_registration_view.html',
            edit_template='polls/response_registration_edit.html',
            report_columns=(('Text', 'text', True, 'message__text', SimpleSorter()),
                            ('Categories', 'categories', True, 'categories__category__name', SimpleSorter())),
            edit_form=NameResponseForm),
    }

    name = models.CharField(max_length=32,
                            help_text="Human readable name.")
    question = models.CharField(_("question"), max_length=160)
    messages = models.ManyToManyField(Message)
    contacts = models.ManyToManyField(Contact, related_name='polls')
    user = models.ForeignKey(User)
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    type = models.SlugField(max_length=8, null=True, blank=True)
    default_response = models.CharField(_("default_response"), max_length=160, null=True, blank=True)
    sites = models.ManyToManyField(Site)
    objects = models.Manager()
    on_site = CurrentSiteManager('sites')
    response_type = models.CharField(max_length=1, choices=RESPONSE_TYPE_CHOICES, default=RESPONSE_TYPE_ALL, null=True,
                                     blank=True)

    class Meta:
        permissions = (
            ("can_poll", "Can send polls"),
            ("can_edit_poll", "Can edit poll rules, categories, and responses"),
        )
        ordering = ["-end_date"]

    @classmethod
    def register_poll_type(cls, field_type, label, parserFunc, \
                           db_type=TYPE_TEXT, \
                           view_template=None, \
                           edit_template=None, \
                           report_columns=None, \
                           edit_form=None):
        """
        Used to register a new question type for Polls.  You can use this method to build new question types that are
        available when building Polls.  These types may just do custom parsing of the SMS text sent in, then stuff
        those results in a normal core datatype, or they may lookup and reference completely custom attributes.

        Arguments are:
           label:       The label used for this field type in the user interface
           field_type:  A slug to identify this field type, must be unique across all field types
           parser:      The function called to turn the raw string into the appropriate type, should take one argument:
                        'value' the string value submitted.
           db_type:     How the value will be stored in the database, can be one of: TYPE_FLOAT, TYPE_TEXT or TYPE_OBJECT
                        (defaults to TYPE_TEXT)
           [view_template]: A template that renders an individual row in a table displaying responses
           [edit_template]: A template that renders an individual row for editing a response
           [report_columns]: the column labels for a table of responses for a poll of a particular type
           [edit_form]: A custom edit form for editing responses
        """
        # set the defaults
        if view_template is None:
            view_template = 'polls/response_custom_view.html'
        if edit_template is None:
            edit_template = 'polls/response_custom_edit.html'
        if report_columns is None:
            report_columns = (('Original Text', 'text'), ('Value', 'custom'))

        Poll.TYPE_CHOICES[field_type] = dict(
            type=field_type, label=label,
            db_type=db_type, parser=parserFunc,
            view_template=view_template,
            edit_template=edit_template,
            report_columns=report_columns,
            edit_form=edit_form)

    @classmethod
    @transaction.atomic
    def create_with_bulk(cls, name, type, question, default_response, contacts, user, is_urgent=False):
        log.info("[Poll.create_with_bulk] TRANSACTION START")
        log.info("[Poll.create_with_bulk] Creating a poll with bulk contacts...")

        log.info("[Poll.create_with_bulk] ignoring blacklisted contacts...")
        if getattr(settings, "BLACKLIST_MODEL", None):

poll/templates/polls/category_edit.html
{% load staticfiles %}
{% load i18n %}

<td class="category_name_col">
    {% if not category %}
        <div class="add_category_header">Add New Category</div>
    {% endif %}
    <script language="javascript">
      $(document).ready(function() {
        // highlight the save button when changes are detected
        $("input,select").change(function() { 
            category_id = '{{ category.pk }}'
            $("#save_" + category_id).addClass("positive");
        });
      });
      
    </script>

  {% if category %}
  
  {% endif %} {{ form.name }} {{ form.name.errors}}</td>
<td class="category_response_col">{{ form.response }} {{form.command.errors}}</td>
<td class="category_priority_col">{{ form.priority }} {{ form.priority.errors }}</td>
<td class="category_color_col" {% if form.color %}style="background-color:#{{ form.color.value }}"{% endif %}>{{ form.color }} {{ form.color.errors }}</td>
<td class="category_default_col">{{ form.default }} {{ form.default.errors }}</td>
<td class="category_options_col">
  
  {% if category %}
      <a style="float:right;padding-top:7px;" href="javascript:void(0);"><img onclick="cancelCategory(this, '{% url 'poll.views.view_category' poll.pk category.pk %}');" src="{% static 'rapidsms/icons/silk/decline.png' %}" alt="" border="0"/></a>
      <div class="buttons">
          <a onclick="saveCategory(this, '{% url 'poll.views.edit_category' poll.pk category.pk %}');" href="javascript:void(0);" id="save_{{ category.pk }}">
              <img src="{% static 'poll/icons/silk/bullet_disk.png' %}" alt=""/>Save
          </a>
      </div>
  {% else %}  
      <a href="javascript:void(0);"><img onclick="cancelAdd(this);" style="float:right;padding-top:6px;" src="{% static 'rapidsms/icons/silk/decline.png' %}" alt="" border="0"/></a>  
      <div class="buttons">
          <a onclick="addCategory(this);" href="javascript:void(0);" id="save_{{ category.pk }}" class="positive">
              <img src="{% static 'rapidsms/icons/silk/add.png' %}" alt=""/>Add
          </a>
      </div>
  {% endif %}
  </td>
</form>

poll/templates/polls/category_view.html
{% load staticfiles %}
{% load i18n %}

<td class="category_name_col">
  {{ category.name }}
</td>
<td class="category_response_col">{{ category.response }}</td>
<td class="category_priority_col">{{ category.priority }}</td>
<td class="category_color_col" {% if category.color %}style="background-color:#{{ category.color }}"{% endif %}>
  &nbsp;
</td>
<td class="category_default_col">
  {% if category.default %}
    <img style="vertical-alignment:bottom;padding-top:7px" src="{% static 'rapidsms/icons/silk/accept.png' %}" alt="This category is default"/>
  {% else %}
    &nbsp;
  {% endif %}
</td>
<td class="category_options_col">
  <a onclick="deleteCategory(this, '{% url 'poll.views.delete_category' poll.pk category.pk %}');" class="negative" style="float:right">
    <img style="vertical-alignment:bottom;padding-top:7px" src="{% static 'rapidsms/icons/silk/delete.png' %}" alt=""/>
  </a>
  <div class="buttons">
    <a onclick="editCategory(this, '{% url 'poll.views.edit_category' poll.pk category.pk %}');" href="javascript:void(0);">
        <img src="{% static 'poll/icons/silk/pencil.png' %}" alt=""/> 
        Edit
    </a>
    {% ifequal poll.type 't' %}
    <a href="{% url 'poll.views.view_rules'  poll.pk category.pk %}" id="save_{{ category.pk }}">
      <img src="{% static 'poll/icons/silk/bullet_wrench.png' %}" alt=""/>Rules ({{ category.rules.all.count }})
    </a>
    {% endifequal %}
  </div>
</td>

poll/templates/polls/layout.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Polls{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'poll/stylesheets/style.css' %}" />
<link rel="stylesheet" href="{% static 'poll/stylesheets/uni-form-generic.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'poll/stylesheets/uni-form.css' %}" type="text/css" />
{% endblock %}


{% block javascripts %}
<script type="text/javascript" src="{% static 'rapidsms/javascripts/jquery-1.9.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'poll/javascripts/jquery-ui-1.7.3.custom.min.js' %}"></script> 
<script src="{% static 'poll/javascripts/uni-form.jquery.js' %}" type="text/javascript"></script>
{% endblock %}

{% block breadcrumbs %}{% if breadcrumbs %}
      <div class="breadcrumb">{% for caption, url in breadcrumbs %}
        {% if url %}<a href="{{ url }}">{{ caption }}</a>{% else %}{{caption}}{% endif %}
        {% if not forloop.last %}
        <span>&raquo;</span>{% endif %}{% endfor %}
      </div>{% endif %}
{% endblock %}

poll/templates/polls/poll_details.html
{% load staticfiles %}
{% load i18n %}

<div class="buttons">
    {% if not poll.start_date %}
    <a onclick="editPollDetails();" href="javascript:void(0);">
        <img src="{% static 'poll/icons/silk/pencil.png' %}" alt=""/> 
        Edit
    </a>
    <form style="border:0px" action="{% url 'poll.views.start_poll' poll.pk %}" method="POST" id="startPollForm">
    {% csrf_token %}
    <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);">
        <img src="{% static 'poll/icons/silk/phone.png' %}" alt=""/> 
        Start Poll
    </a>
    </form>
    {% endif %}
    {% if poll.start_date and not poll.end_date %}
    <form style="border:0px" action="{% url 'poll.views.end_poll' poll.pk %}" method="POST" id="closePollForm">
    <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);">
        <img src="{% static 'rapidsms/icons/silk/delete.png' %}" alt=""/> 
        Close Poll
    </a>
    </form>    
    {% endif %}
</div>
<div class="name">{{ poll.name }} 
  <span class="participants">({{ poll.contacts__count }} participant{{ poll.contacts__count|pluralize }})</span>
</div>
<div class="question">{{ poll.question }}</div>
<div class="response">Response: {{ poll.default_response }}</div>

poll/templates/polls/poll_edit.html
{% load staticfiles %}
{% load i18n %}

<div class="name">Edit '{{poll.name}}'</div>

{% load uni_form_tags %}

<form action="{% url 'poll.views.edit_poll' poll.pk %}" method="post" class="uniForm">
<fieldset>
{{form|as_uni_form}}

<div class="buttons" style="float:left;margin-bottom:10px;margin-top:10px">
  <a onclick="showPollDetails('{{ poll.pk }}');" href="javascript:void(0);" class="negative">
    <img src="{% static 'rapidsms/icons/silk/decline.png' %}" alt=""/> 
    Cancel
  </a>
  <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);">
    <img src="{% static 'poll/icons/silk/disk.png' %}" alt=""/> 
    Save Poll Details
  </a>
</div>
</fieldset>
</form>

poll/templates/polls/poll_report_numeric.html
<div id="poll_header">
<div class="buttons">
    <a href="javascript:void(0)" onclick="$.get('{% url 'poll.views.demo' poll.pk %}')" style="float:right"> 
      <img border="0" src="/static/rapidsms/icons/silk/package_go.png" alt=""/>Send Alerts
    </a>
</div>
<div class="name">{{ poll.name }} :
  <span class="participants">{{ poll.contacts.count }} participant{{ poll.contacts.count|pluralize }}, {{ poll.responses.count }} total response{{ poll.responses.count|pluralize }} ({{ response_rate|floatformat }}% response rate)</span>
</div>
<div class="question">{{ poll.question }}</div>
<div class="response">Response: {{ poll.default_response }}</div>
</div>
<table width="100%" class="poll_table"> 
    <thead>
        <th>Location</th>
        <th>Total</th>
        <th>Max</th>
        <th>Min</th>
        <th>Avg</th>
        <th>StdDev</th>
    </thead>
    <tbody>
        {% for location_data in report_rows %}
            <tr>
                <td>
                    <a href="javascript:void(0)" onclick="$('#poll_report').load('{% url 'poll-report-location-module' poll.pk location_data.location_id %}')">
                        {{ location_data.location_name }}
                    </a>
                </td>   
                <td>{{ location_data.value_float__sum|floatformat }}</td>
                <td>{{ location_data.value_float__max|floatformat }}</td>
                <td>{{ location_data.value_float__min|floatformat }}</td>
                <td>{{ location_data.value_float__avg|floatformat }}</td>
                <td>{{ location_data.value_float__stddev|floatformat }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

poll/templates/polls/poll_view.html
{% extends "polls/layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Polls{% endblock %}

{% block content %}

<script type="text/javascript">

	function ajax_loading(element)
	{
    	var t=$(element) ;
    	var offset = t.offset();
    	var dim = {
        	left:    offset.left,
        	top:    offset.top,
        	width:    t.outerWidth(),
        	height:    t.outerHeight()
    	};
    	$('<div class="ajax_loading"></div>').css({
        	position:    'absolute',
        	left:        dim.left + 'px',
        	top:        dim.top + 'px',
        	width:        dim.width + 'px',
        	height:        dim.height + 'px'
    	}).appendTo(document.body).show();
	}
	// Add a new box for entering a new category
	function addNewCategoryBox() {
		var newBox = $("#new_category_box").clone();
		newBox.load( "{% url 'poll.views.add_category' poll.pk %}", function() {
			newBox.show();
			newBox.id = "category_box_" + Math.floor((new Date()).getTime() / 1000);
			$('#poll_table').append(newBox);
		});
	}
	
	$(document).ready(function() {
		// hide our new category template
		$('#new_category_box').hide();
		showPollDetails();
		// if no categories, show the add new category form
		if ({{category_count}} == 0) {
			addNewCategoryBox();
		}
	});
	
	function showPollDetails() {
	  $("#poll_header").load("{% url 'poll.views.view_poll_details' poll.pk %}");
	}
	
	function deleteCategory(link, url) {
	  if (confirm("Are you sure you want to delete this category?")) {
      $.post(url, function(data) {
        $(link).parents("tr").remove();
      }); 
    }
  }
  
  function editCategory(link, url) {
    $(link).parents("tr").load(url);
    selected = $(("#selection_" + category_id));
    selected.addClass('form_selected');
    selected.removeClass('form_unselected');
  }
	
  function saveCategory(link, form_action) {
      form_data = $(link).parents("form").serializeArray();
      $(link).parents("tr").load(form_action, form_data);
  }
  
  function addCategory(link) {
      form_data = $(link).parents("form").serializeArray();
      $(link).parents("tr").load('{% url 'poll.views.add_category' poll.pk %}', form_data);    
  }
  
  function cancelAdd(link) {
      if (confirm("Are you sure you want to cancel this new category?")) {
          $(link).parents("tr").remove();
      }
  }
	
	function cancelCategory(link, url) {
        $(link).parents("tr").load(url);
	}
	
	function editPollDetails() {
	  $("#poll_header").load('{% url 'poll.views.edit_poll' poll.pk %}');
	}
	
	function submitForm(link, resultDiv) {
        ajax_loading(resultDiv);
       
	    form = $(link).parents("form");
        form_data = form.serializeArray();
        $(resultDiv).load(form.attr("action"), form_data,function() {
            $('.ajax_loading').remove();

        });

	}
	
	// Trap our ajax errors and put them where we can see them
	$.ajaxSetup({
		error:function(x,e){
			if(x.status==0){
				$("#error").html("Oopsie, network not found.");
			} else if(x.status>=400){
				$("#error").html(x.responseText);	
			}
		}
	});
	
</script>
  
<div id="poll_header">
</div>

<form action="">
{% csrf_token %}
<table width="100%" class="poll_table" id="poll_table">
<thead>
<tr>
<th class="category_name_col">Name</th>
<th class="category_response_col">Response Message</th>
<th class="category_priority_col">Priority</th>
<th class="category_color_col">Color</th>
<th class="category_default_col">Default</th>
<th class="category_options_col"></th>
</tr>
</thead>
{% for category in categories %}
    <tr>
        {% include "polls/category_view.html" %}
    </tr>
{% endfor %}
<tr id="new_category_box">
</tr>
</table>
</form>
<br/>
<div class="buttons">
    <a href="javascript:addNewCategoryBox();" style="float:left">
      <img border="0" src="{% static 'rapidsms/icons/silk/add.png' %}" alt=""/>Add New Category
    </a>
</div>
<br/><br/>
<div id="error"></div>
{% endblock %}

poll/templates/polls/response_base_view.html
{% load staticfiles %}
{% load i18n %}

{% block message_information %}
    <td class="response_sender_col">
      {% if response.message.connection.contact %}
        {{ response.message.connection.contact }}
      {% else %}
        {{ response.message.connection.identity }}
      {% endif %} 
       at {{ response.message.date|date:"d/m/Y H:i" }}
    </td>
{% endblock %}
{% block remaining_content %}
{% endblock %}
{% block actions_cell %}
    <td class="response_options_col">
    {% block actions_content %}
      <a onclick="deleteResponse(this, '{% url 'poll.views.delete_response' response.pk %}');" class="negative" style="float:right">
      <img style="vertical-alignment:bottom;padding-top:7px" src="{% static 'rapidsms/icons/silk/delete.png' %}" alt=""/>
      </a>
      <div class="buttons">
        <a onclick="editResponse(this, '{% url 'poll.views.edit_response' response.pk %}');" href="javascript:void(0);">
            <img src="{% static 'poll/icons/silk/pencil.png' %}" alt=""/> 
            Edit
        </a>
      </div>
    {% endblock %}
    </td>
{% endblock %}

poll/templates/polls/response_custom_edit.html
{% extends "polls/response_base_edit.html" %}
{% block remaining_content %}
<td class="center response_text_col">
    {{ form.value }} {{ form.value.errors }}
</td>
<td class="center response_custom_col">
      {% ifequal db_type 'text' %}
          {{ response.eav.poll_text_value }}
      {% else %}
          {% ifequal db_type 'float' %}
              {{ response.eav.poll_number_value
          {% else %}
              {% ifequal db_type 'object' %}
                  {{ response.eav.poll_location_value }}
              {% endifequal %}
          {% endifequal %}
      {% endifequal %}
</td>
{% endblock %}

poll/templates/polls/response_custom_view.html
{% extends "polls/response_base_view.html" %}
{% block remaining_content %} 
    <td class="center response_text_col">
        {{ response.message.text }}
    </td>
    <td class="center response_custom_col">
      {% ifequal db_type 'text' %}
          {{ response.eav.poll_text_value }}
      {% else %}
          {% ifequal db_type 'float' %}
              {{ response.eav.poll_number_value
          {% else %}
              {% ifequal db_type 'object' %}
                  {{ response.eav.poll_location_value }}
              {% endifequal %}
          {% endifequal %}
      {% endifequal %}
    </td>
{% endblock %}

poll/templates/polls/response_numeric_view.html
{% extends "polls/response_base_view.html" %}
{% block remaining_content %}
    <td class="center response_text_col">
      {{ response.message.text }}
    </td>
    <td class="response_value_col center">
      {{ response.eav.poll_number_value|floatformat:3 }}
    </td>
    <td class="response_categories_col">
      {% if response.categories %}
        <ul class="category_list">
          {% for responsecategory in response.categories.all %}
          <li {% if responsecategory.category.color %}style="width:100%;background-color:#{{ responsecategory.category.color }}"{% endif %}>
            {{ responsecategory.category.name }}
          </li>
          {% endfor %}
        </ul>
      {% endif %}
    </td>
{% endblock %}

poll/templates/polls/translation.html
<style>
    #id_value{

    }
    #id_field{

    }

   .trans  label {
  padding-top: 6px;
  font-size: 13px;
  line-height: 18px;
  float: right;
  width: 130px;
  text-align: left;
  color: #404040;
}
</style>
<div class="trans">
<table>
    <form class ="trans" action="{% url translate %}" method="Post">
        {{ translation_form.as_table }}
    </form>

   <tr><td> <a href="Javascript:void(0)" onclick="">ADD</a></td></tr>

    </table>
</div>